---
- name: Stop and remove lab
  docker_container:
    name:  "{{ UUID }}"
    state: absent
  register: container_removal

- name: Stop and remove lab backend
  docker_container:
    name:  "{{ UUID }}-back"
    state: absent
  register: container_removal

- name: Display removal status
  debug:
    var: container_removal

- name: Remove lab folder
  file:
    path: "{{ servers_remote_folder }}/{{ UUID }}"
    state: absent
  become: true
