version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  dramatiq:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dramatiq
    restart: always
    command: dramatiq api.tasks --processes 4 --skip-logging
    depends_on:
      - redis
    env_file:
      - ../.env.example


