version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery
    restart: always
    command: celery -A api.celery_app worker --loglevel=info  --concurrency=4
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0


